#!/usr/bin/env python3
"""Add the ReiFlix Android host to a real Flet Cookiecutter build template.

Flet's ``--template`` option accepts a Cookiecutter repository, not an Android
overlay.  CI clones the official Flet template, then this script places the
overlay beside that template and installs a Cookiecutter post-generation hook.
The hook runs *after* Flet renders the Flutter project and *before* Gradle
builds it, so the Kotlin sources, manifest entries, resources, and dependencies
belong to the Android project that produces the APK.
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path


HOOK = r'''# Generated by ReiFlix: runs in the rendered Flutter project before Gradle.
from __future__ import annotations

import shutil
import xml.etree.ElementTree as ET
from pathlib import Path

ANDROID = "http://schemas.android.com/apk/res/android"
ET.register_namespace("android", ANDROID)
root = Path.cwd()
overlay = Path(__file__).resolve().parents[1] / "reiflix_android_overlay" / "app"
app = root / "android" / "app"
if not app.is_dir():
    raise RuntimeError(f"Rendered Flet project has no Android app module: {app}")

# Kotlin sources are copied into the rendered app module, retaining the package
# used by pyproject.toml (com.reiflix.reiflix_local).
source = overlay / "src" / "main" / "kotlin"
destination = app / "src" / "main" / "kotlin"
shutil.copytree(source, destination, dirs_exist_ok=True)

# Keep the generated Flutter launch resources.  ReiFlix adds only its own
# player/host theme resource, avoiding replacement of Flutter's LaunchTheme.
values = app / "src" / "main" / "res" / "values"
values.mkdir(parents=True, exist_ok=True)
shutil.copy2(overlay / "src" / "main" / "res" / "values" / "styles.xml", values / "reiflix_styles.xml")

manifest_path = app / "src" / "main" / "AndroidManifest.xml"
tree = ET.parse(manifest_path)
manifest = tree.getroot()
application = manifest.find("application")
if application is None:
    raise RuntimeError("Rendered Flet AndroidManifest has no application element")
name = f"{{{ANDROID}}}name"
activities = application.findall("activity")
main = next((activity for activity in activities if activity.get(name) in {".MainActivity", "com.reiflix.reiflix_local.MainActivity"}), None)
if main is None:
    raise RuntimeError("Rendered Flet manifest has no MainActivity to replace")
main.set(name, "com.reiflix.reiflix_local.MainActivity")
main.set(f"{{{ANDROID}}}launchMode", "singleTop")
main.set(f"{{{ANDROID}}}configChanges", "orientation|screenSize|keyboardHidden")

# Reiflix bridge deep-link retained alongside Flet's launcher intent filter.
bridge = ET.SubElement(main, "intent-filter")
ET.SubElement(bridge, "action", {f"{{{ANDROID}}}name": "android.intent.action.VIEW"})
ET.SubElement(bridge, "category", {f"{{{ANDROID}}}name": "android.intent.category.DEFAULT"})
ET.SubElement(bridge, "category", {f"{{{ANDROID}}}name": "android.intent.category.BROWSABLE"})
ET.SubElement(bridge, "data", {f"{{{ANDROID}}}scheme": "reiflix", f"{{{ANDROID}}}host": "native"})

player_name = "com.reiflix.reiflix_local.NativePlayerActivity"
if not any(activity.get(name) == player_name for activity in application.findall("activity")):
    ET.SubElement(application, "activity", {
        name: player_name,
        f"{{{ANDROID}}}theme": "@style/ReiFlixPlayerTheme",
        f"{{{ANDROID}}}configChanges": "orientation|screenSize|keyboardHidden",
        f"{{{ANDROID}}}screenOrientation": "sensorLandscape",
        f"{{{ANDROID}}}exported": "false",
    })
tree.write(manifest_path, encoding="utf-8", xml_declaration=True)

dependencies = [
    "androidx.activity:activity-ktx:1.9.3",
    "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0",
    "androidx.documentfile:documentfile:1.0.1",
    "androidx.media3:media3-exoplayer:1.5.1",
    "androidx.media3:media3-ui:1.5.1",
    "androidx.credentials:credentials:1.3.0",
    "androidx.credentials:credentials-play-services-auth:1.3.0",
    "com.google.android.libraries.identity.googleid:googleid:1.1.1",
]
gradle = next((app / candidate for candidate in ("build.gradle.kts", "build.gradle") if (app / candidate).is_file()), None)
if gradle is None:
    raise RuntimeError("Rendered Flet app module has no Gradle build file")
existing = gradle.read_text(encoding="utf-8")
if "androidx.media3:media3-exoplayer:1.5.1" not in existing:
    if gradle.suffix == ".kts":
        block = "\n// ReiFlix native host dependencies\ndependencies {\n" + "".join(f'    implementation("{item}")\n' for item in dependencies) + "}\n"
    else:
        block = "\n// ReiFlix native host dependencies\ndependencies {\n" + "".join(f"    implementation '{item}'\n" for item in dependencies) + "}\n"
    gradle.write_text(existing + block, encoding="utf-8")
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", type=Path, required=True)
    parser.add_argument("--overlay", type=Path, default=Path("android"))
    args = parser.parse_args()
    template = args.template.resolve()
    overlay = args.overlay.resolve()
    if not (template / "cookiecutter.json").is_file():
        parser.error(f"Flet template is not a Cookiecutter repository: {template}")
    source = overlay / "app"
    required = [
        source / "src/main/kotlin/com/reiflix/reiflix_local/MainActivity.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/NativeMailbox.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/SafScanner.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/NativePlayerActivity.kt",
        source / "src/main/kotlin/com/reiflix/reiflix_local/GoogleIdentity.kt",
        source / "src/main/res/values/styles.xml",
    ]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        parser.error("Android host overlay is incomplete: " + ", ".join(missing))

    target = template / "reiflix_android_overlay"
    shutil.rmtree(target, ignore_errors=True)
    shutil.copytree(source, target / "app")
    hooks = template / "hooks"
    hooks.mkdir(exist_ok=True)
    hook = hooks / "post_gen_project.py"
    previous = hook.read_text(encoding="utf-8") if hook.exists() else ""
    hook.write_text(previous + "\n\n" + HOOK, encoding="utf-8")
    print(f"Prepared native ReiFlix host in Cookiecutter template: {template}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
